#include "AppTypes.h"

const std::array<CommandDescriptor, COMMAND_COUNT> COMMANDS = {{
    {"record_start", "RECORD", "Transport", "record", true},
    {"stop_replay", "STOP + REPLAY", "Transport", "replay", true},
    {"record_stop", "Stop Recording", "Transport", "normal", false},
    {"record_toggle", "Record Toggle", "Transport", "normal", false},
    {"rec_review", "Rec Review", "Transport", "normal", true},
    {"play", "Play", "Playback", "normal", false},
    {"pause", "Pause", "Playback", "normal", false},
    {"stop_playback", "Stop Playback", "Playback", "normal", false},
    {"awb", "Auto White", "Camera", "normal", true},
    {"auto_iris", "Auto Iris", "Camera", "normal", false},
    {"iris_up", "Iris +", "Camera", "normal", false},
    {"iris_down", "Iris -", "Camera", "normal", false},
    {"gain_up", "Gain +", "Camera", "normal", false},
    {"gain_down", "Gain -", "Camera", "normal", false},
    {"nd_up", "ND +", "Camera", "normal", false},
    {"nd_down", "ND -", "Camera", "normal", false},
    {"shutter_up", "Shutter +", "Camera", "normal", false},
    {"shutter_down", "Shutter -", "Camera", "normal", false},
    {"zoom_in", "Zoom In", "Lens", "normal", false},
    {"zoom_out", "Zoom Out", "Lens", "normal", false},
    {"focus_near", "Focus Near", "Lens", "normal", false},
    {"focus_far", "Focus Far", "Lens", "normal", false},
    {"assign_1", "Assign 1", "Assignable", "normal", false},
    {"assign_2", "Assign 2", "Assignable", "normal", false},
    {"assign_3", "Assign 3", "Assignable", "normal", false},
    {"assign_4", "Assign 4", "Assignable", "normal", false},
    {"assign_5", "Assign 5", "Assignable", "normal", false},
    {"assign_6", "Assign 6", "Assignable", "normal", false},
    {"assign_7", "Assign 7", "Assignable", "normal", false},
    {"assign_8", "Assign 8", "Assignable", "normal", false},
    {"assign_9", "Assign 9", "Assignable", "normal", false},
    {"assign_10", "Assign 10", "Assignable", "normal", false},
}};

const std::array<CameraStateDescriptor, CAMERA_STATE_COUNT> CAMERA_STATES = {{
    {"recording", "Recording", "Transport", "bool", false},
    {"playback", "Playback", "Transport", "bool", false},
    {"ready", "Camera Ready", "Transport", "bool", false},
    {"writing", "Media Writing", "Transport", "bool", false},
    {"buffer_ready", "Slow-mo Buffer Ready", "Transport", "bool", false},
    {"white_balance", "White Balance", "Exposure", "string", true},
    {"white_balance_k", "White Balance K", "Exposure", "int", false},
    {"white_balance_mode", "WB Mode", "Exposure", "string", false},
    {"gain_db", "Gain", "Exposure", "float", true},
    {"exposure_index", "Exposure Index", "Exposure", "int", false},
    {"iris_f", "Iris", "Exposure", "float", true},
    {"nd", "ND", "Exposure", "string", true},
    {"shutter", "Shutter", "Exposure", "string", true},
    {"sq_fps", "S&Q FPS", "Recording", "float", true},
    {"gamma", "Gamma", "Image", "string", false},
    {"mlut", "MLUT", "Image", "string", false},
    {"focus", "Focus", "Lens", "string", false},
    {"zoom", "Zoom", "Lens", "string", false},
    {"atw", "ATW", "Exposure", "bool", false},
    {"auto_iris", "Auto Iris", "Exposure", "bool", false},
    {"camera_mode", "Camera Mode", "Camera", "string", false},
    {"media_status", "Media", "Camera", "string", false},
    {"timecode", "Timecode", "Camera", "string", false},
}};
